# Wire up travis
language: python
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"


# command to install dependencies
install:
  - python -m pip install -e .[testing]
  - python -m pip install flake8

# command to run tests
script:
  - flake8 .
  - pytest --cov=gdcapiwrapper

after_success:
  - coveralls

notifications:
  slack: mpba:fBrjUWlUSa3XKeCA8zFsTFu2